[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[[tool.mypy.overrides]]
module = ["pytest.*", "pytest_asyncio.*", "pyroute2.*"]
ignore_missing_imports = true
